version: "3.9"
services:
  nginx_custom_vay:
    build: .
    image: nginx_custom_vay:${NGINX_TAG}
    container_name: nginx-custom-vay
    volumes:
     - ./data:/usr/share/nginx/html
       # - ./set-variables.sh:/set-variables.sh
       #command: bash -c "sleep 5 && chmod 755 /set-variables.sh && /set-variables.sh"
    ports:
     - "10080:10080"       
     - "10443:10443"
