version: "3.9"
services:
  nginx_custom_vay:
    build: .
    image: nginx_custom_vay:${NGINX_TAG}
    container_name: nginx-custom-vay
    volumes:
     - ./certificates:/etc/nginx/certs
     - nginx_config:/etc/nginx
    ports:
     - "10080:80"       
     - "10443:443"

volumes:
  nginx_config:
    external: true
